# Perform data exploration for data science

Use the code in this notebook to perform data exploration for data science.

##### Load data into a dataframe

In [1]:
# Azure storage access info for open dataset diabetes
blob_account_name = "azureopendatastorage"
blob_container_name = "ojsales-simulatedcontainer"
blob_relative_path = "oj_sales_data"
blob_sas_token = r"" # Blank since container is Anonymous access
    
# Set Spark config to access  blob storage
wasbs_path = f"wasbs://%s@%s.blob.core.windows.net/%s" % (blob_container_name, blob_account_name, blob_relative_path)
spark.conf.set("fs.azure.sas.%s.%s.blob.core.windows.net" % (blob_container_name, blob_account_name), blob_sas_token)
print("Remote blob path: " + wasbs_path)
    
# Spark reads csv
df = spark.read.csv(wasbs_path, header=True)

StatementMeta(, 53665287-56c9-4d2b-92e2-52d1ec9b86a7, 3, Finished, Available, Finished, False)

Remote blob path: wasbs://ojsales-simulatedcontainer@azureopendatastorage.blob.core.windows.net/oj_sales_data

In [ ]:
# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Replace all instances of "." with " " in column: 'Brand'
    df['Brand'] = df['Brand'].str.replace(".", " ", case=False, regex=False)
    # Capitalize the first character in column: 'Brand'
    df['Brand'] = df['Brand'].str.title()
    return df

df_clean = clean_data(df.copy())
display(df_clean)

In [1]:
import pandas as pd

df = df.toPandas()
df = df.sample(n=500, random_state=1)
    
df['WeekStarting'] = pd.to_datetime(df['WeekStarting'])
df['Quantity'] = df['Quantity'].astype('int')
df['Advert'] = df['Advert'].astype('int')
df['Price'] = df['Price'].astype('float')
df['Revenue'] = df['Revenue'].astype('float')
    
df = df.reset_index(drop=True)
df.head(4)

StatementMeta(, a43ad3fd-7500-49d0-9a26-fb105d6778df, 3, Finished, Available, Finished, False)

NameError: name 'df' is not defined

In [3]:
df.head(4)

StatementMeta(, 53665287-56c9-4d2b-92e2-52d1ec9b86a7, 23, Finished, Available, Finished, False)

  WeekStarting Store        Brand  Quantity  Advert  Price   Revenue
0   1991-10-17   947  minute.maid     13306       1   2.42  32200.52
1   1992-03-26  1293    dominicks     18596       1   1.94  36076.24
2   1991-08-15  2278    dominicks     17457       1   2.14  37357.98
3   1992-09-03  2175    tropicana      9652       1   2.07  19979.64

In [4]:
# Code generated by Data Wrangler for pandas DataFrame

def clean_data(df):
    # Replace all instances of "." with " " in column: 'Brand'
    df['Brand'] = df['Brand'].str.replace(".", " ", case=False, regex=False)
    # Capitalize the first character in column: 'Brand'
    df['Brand'] = df['Brand'].str.title()
    return df
    
df = clean_data(df)

StatementMeta(, 53665287-56c9-4d2b-92e2-52d1ec9b86a7, 42, Finished, Available, Finished, False)

In [7]:
df.head(4)

StatementMeta(, 53665287-56c9-4d2b-92e2-52d1ec9b86a7, 59, Finished, Available, Finished, False)

  WeekStarting Store        Brand  Quantity  Advert  Price   Revenue
0   1991-10-17   947  Minute Maid     13306       1   2.42  32200.52
1   1992-03-26  1293    Dominicks     18596       1   1.94  36076.24
2   1991-08-15  2278    Dominicks     17457       1   2.14  37357.98
3   1992-09-03  2175    Tropicana      9652       1   2.07  19979.64

In [6]:
df['Brand'].unique()

StatementMeta(, 53665287-56c9-4d2b-92e2-52d1ec9b86a7, 44, Finished, Available, Finished, False)

array(['Minute Maid', 'Dominicks', 'Tropicana'], dtype=object)